name: Trigger CI/CD Workflow (PR de Fork)

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main  # Ou outra branch alvo

jobs:
  trigger:
    uses: GabrielLLR/repo-ci-cd/.github/workflows/pr-validation-and-jira.yml@main
