name: Trigger CI/CD Workflow (PR de Fork)

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Construir a URL RAW do Swagger.yaml
        id: get_raw_url
        run: |
          RAW_URL="https://raw.githubusercontent.com/${{ github.event.pull_request.head.repo.full_name }}/${{ github.event.pull_request.head.ref }}/swagger.yaml"
          echo "SWAGGER_RAW_URL=$RAW_URL" >> $GITHUB_ENV

      - name: Exibir URL do Arquivo Swagger (Debug)
        run: |
          echo "Swagger YAML disponível em: ${{ env.SWAGGER_RAW_URL }}"

      - name: Acionar workflow no `repo-ci-cd`
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.REPO_ACCESS_TOKEN }}" \
            https://api.github.com/repos/GabrielLLR/repo-ci-cd/actions/workflows/pr-validation-and-jira.yml/dispatches \
            -d "{\"ref\":\"main\", \"inputs\": {\"SWAGGER_FILE_URL\": \"${{ env.SWAGGER_RAW_URL }}\"}}"
